<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Celie - Refúgio Seguro</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />

  <link
    href="https://fonts.googleapis.com/css2?family=Merriweather:wght@700&family=Open+Sans&display=swap"
    rel="stylesheet"
  />

  <link rel="stylesheet" href="/assets/css/application.css" />
</head>

<body>
<nav class="navbar navbar-light bg-white shadow-sm fixed-top px-5" style="padding-top:0.25rem; padding-bottom:0.25rem; min-height:40px;">
  <a class="navbar-brand d-flex align-items-center" href="/">
    <img src="/assets/images/logo.png" alt="Celie logo" width="50" class="me-2" />
  </a>
</nav>


  <main class="container mt-5 pt-4">
    <?php require '_flash_message.phtml'; ?>

    <section >
      <?php require $view ?>
    </section>
  </main>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/assets/js/application.js"></script>
</body>

</html>
