<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Celie - Login</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />

  <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@700&family=Open+Sans&display=swap" rel="stylesheet" />

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />

  <link rel="stylesheet" href="/assets/css/login.css" />
</head>

<body class="d-flex flex-column align-items-center justify-content-center min-vh-100 bg-beige-light">

  <img src="/assets/images/logo.png" alt="Logo Celie" style="width: 100px; margin-bottom: 2rem;" />

  <div class="card p-4 shadow-sm" style="max-width: 400px; width: 90%;">
    <div class="card-body">
      <h4 class="card-title text-center mb-4">Login</h4>

      <?php require '_flash_message.phtml'; ?>
      <?php require $view ?>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/assets/js/application.js"></script>
</body>

</html>
